[pytest]
addopts = --maxfail=1 --cov=app --cov-report=term-missing --cov-report=xml --cov-config=.coveragerc
filterwarnings =
    ignore:Valid config keys have changed in V2::pydantic
    ignore:on_event is deprecated.*:DeprecationWarning
