"""Collection des schemas exposés aux routers FastAPI."""
from __future__ import annotations

from .alerts import AlertOut
from .clients import (
    ClientCreate,
    ClientOut,
    ClientRecipientOut,
    ClientStripeSubscriptionOut,
    ClientSubscriptionOut,
    ClientUpdate,
    ListingStatus,
)
from .email import AdminEmailConfig, AdminEmailConfigUpdate, EmailTestRequest, EmailTestResponse
from .establishments import DirectorOut, EstablishmentDetailOut, EstablishmentOut
from .google import (
    GoogleFindPlaceCandidateOut,
    GoogleFindPlaceDebugResponse,
    GoogleRetryConfigOut,
    GoogleRetryConfigUpdate,
    GoogleRetryRule,
    ManualGoogleCheckResponse,
)
from .linkedin import LinkedInCheckResponse, LinkedInDebugResponse
from .public_contact import PublicContactRequest, PublicContactResponse
from .public_catalog import PublicNafCategoryOut
from .public_stripe import (
    PublicStripeCheckoutRequest,
    PublicStripeCheckoutResponse,
    PublicStripePortalRequest,
    PublicStripePortalResponse,
    PublicStripePortalSessionRequest,
    PublicStripePortalSessionResponse,
    PublicStripeSubscriptionCategoryOut,
    PublicStripeSubscriptionInfoRequest,
    PublicStripeSubscriptionInfoResponse,
    PublicStripeUpdateRequest,
    PublicStripeUpdateResponse,
    PublicStripeUpdatePreviewRequest,
    PublicStripeUpdatePreviewResponse,
    StripePlanKey,
)
from .regions import DepartmentOut, RegionOut
from .naf import (
    NafCategoryCreate,
    NafCategoryOut,
    NafCategoryStats,
    NafCategoryUpdate,
    NafCategorySubCategoryLink,
    NafSubCategoryCreate,
    NafSubCategoryOut,
    NafSubCategoryStats,
    NafSubCategoryUpdate,
)
from .stats import (
    DailyAlertMetricPoint,
    DailyApiMetricPoint,
    DailyGoogleStatusPoint,
    DailyMetricPoint,
    DailyRunOutcomePoint,
    DashboardMetrics,
    DashboardRunBreakdown,
    GoogleListingAgeBreakdown,
    GoogleStatusBreakdown,
    StatsSummary,
)
from .sync import (
    DeleteRunResult,
    RunEmailSummary,
    RunEstablishmentSummary,
    RunSummaryStats,
    RunUpdatedEstablishmentSummary,
    SyncRequest,
    SyncRunOut,
    SyncRunReport,
    SyncStateOut,
)
from .tools import (
    SireneNewBusinessOut,
    SireneNewBusinessesRequest,
    SireneNewBusinessesResponse,
)
from .stripe_settings import (
    AdminStripeSettingsOut,
    AdminStripeSettingsUpdate,
    AdminStripeSettingsUpdateResponse,
    PublicStripeSettingsOut,
)

__all__ = [
    "AdminEmailConfig",
    "AdminEmailConfigUpdate",
    "AlertOut",
    "ClientCreate",
    "ClientOut",
    "ClientRecipientOut",
    "ClientStripeSubscriptionOut",
    "ClientSubscriptionOut",
    "ClientUpdate",
    "DailyAlertMetricPoint",
    "DailyApiMetricPoint",
    "DailyGoogleStatusPoint",
    "DailyMetricPoint",
    "DailyRunOutcomePoint",
    "DashboardMetrics",
    "DashboardRunBreakdown",
    "DepartmentOut",
    "DeleteRunResult",
    "DirectorOut",
    "EmailTestRequest",
    "EmailTestResponse",
    "EstablishmentDetailOut",
    "EstablishmentOut",
    "GoogleListingAgeBreakdown",
    "GoogleFindPlaceCandidateOut",
    "GoogleFindPlaceDebugResponse",
    "GoogleRetryConfigOut",
    "GoogleRetryConfigUpdate",
    "GoogleRetryRule",
    "GoogleStatusBreakdown",
    "LinkedInCheckResponse",
    "LinkedInDebugResponse",
    "ListingStatus",
    "ManualGoogleCheckResponse",
    "NafCategoryCreate",
    "NafCategoryOut",
    "NafCategoryStats",
    "NafCategoryUpdate",
    "NafCategorySubCategoryLink",
    "NafSubCategoryCreate",
    "NafSubCategoryOut",
    "NafSubCategoryStats",
    "NafSubCategoryUpdate",
    "RunEmailSummary",
    "RunEstablishmentSummary",
    "RunSummaryStats",
    "RunUpdatedEstablishmentSummary",
    "StatsSummary",
    "SyncRequest",
    "SyncRunOut",
    "SyncRunReport",
    "SyncStateOut",
    "PublicContactRequest",
    "PublicContactResponse",
    "AdminStripeSettingsOut",
    "AdminStripeSettingsUpdate",
    "AdminStripeSettingsUpdateResponse",
    "PublicStripeSettingsOut",
    "PublicNafCategoryOut",
    "PublicStripeCheckoutRequest",
    "PublicStripeCheckoutResponse",
    "PublicStripePortalRequest",
    "PublicStripePortalResponse",
    "PublicStripePortalSessionRequest",
    "PublicStripePortalSessionResponse",
    "PublicStripeSubscriptionCategoryOut",
    "PublicStripeSubscriptionInfoRequest",
    "PublicStripeSubscriptionInfoResponse",
    "PublicStripeUpdateRequest",
    "PublicStripeUpdateResponse",
    "PublicStripeUpdatePreviewRequest",
    "PublicStripeUpdatePreviewResponse",
    "StripePlanKey",
    "RegionOut",
    "SireneNewBusinessOut",
    "SireneNewBusinessesRequest",
    "SireneNewBusinessesResponse",
]
